# Generated by Django 5.0.3 on 2026-01-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdriveappointment',
            name='date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='testdriveappointment',
            name='time',
            field=models.CharField(max_length=40),
        ),
    ]
