# Generated by Django 5.0.3 on 2026-01-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_api', '0002_alter_testdriveappointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('budget', models.CharField(blank=True, max_length=20)),
                ('body_type', models.CharField(blank=True, max_length=60)),
                ('fuel_type', models.CharField(blank=True, max_length=120)),
                ('year', models.CharField(blank=True, max_length=15)),
                ('mileage', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
