# Generated by Django 5.0.3 on 2026-01-15 15:41
from decimal import Decimal

from django.db import migrations, models

def seed_initial_data(apps, schema_editor):
    VehicleInformation = apps.get_model("dealership_api", "VehicleInformation")

    seed_vehicles = [
        {
            "make": "Toyota",
            "model": "Corolla",
            "price": Decimal("12500.00"),
            "fuel_type": "Petrol",
            "year": "2017",
            "mileage": "98000",
        },
        {
            "make": "Volkswagen",
            "model": "Golf",
            "price": Decimal("14900.00"),
            "fuel_type": "Diesel",
            "year": "2018",
            "mileage": "112000",
        },
        {
            "make": "BMW",
            "model": "320d",
            "price": Decimal("18900.00"),
            "fuel_type": "Diesel",
            "year": "2016",
            "mileage": "158000",
        },
        {
            "make": "Audi",
            "model": "A4",
            "price": Decimal("21500.00"),
            "fuel_type": "Diesel",
            "year": "2017",
            "mileage": "134000",
        },
        {
            "make": "Ford",
            "model": "Focus",
            "price": Decimal("9900.00"),
            "fuel_type": "Petrol",
            "year": "2015",
            "mileage": "145000",
        },
        {
            "make": "Mercedes-Benz",
            "model": "C220",
            "price": Decimal("23900.00"),
            "fuel_type": "Diesel",
            "year": "2017",
            "mileage": "121000",
        },
        {
            "make": "Hyundai",
            "model": "Tucson",
            "price": Decimal("17900.00"),
            "fuel_type": "Petrol",
            "year": "2019",
            "mileage": "87000",
        },
        {
            "make": "Tesla",
            "model": "Model 3",
            "price": Decimal("27900.00"),
            "fuel_type": "Electric",
            "year": "2020",
            "mileage": "65000",
        },
    ]

    for v in seed_vehicles:
        VehicleInformation.objects.get_or_create(
            make=v["make"],
            model=v["model"],
            year=v["year"],
            defaults={
                "price": v["price"],
                "fuel_type": v["fuel_type"],
                "mileage": v["mileage"],
            },
        )

class Migration(migrations.Migration):

    dependencies = [
        ('dealership_api', '0003_vehicleinformationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(blank=True, max_length=120)),
                ('year', models.CharField(blank=True, max_length=15)),
                ('mileage', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RunPython(seed_initial_data),
    ]
